---
{{- if .Values.stan.nats.serviceRoleAuth.enabled }}
apiVersion: nats.io/v1alpha2
kind: NatsServiceRole
metadata:
  name: {{ .Values.serviceAccountName }}
  labels:
    nats_cluster: {{ .Values.stan.nats.serviceRoleAuth.natsClusterName }}
spec:
  permissions:
    publish: [">"]
    subscribe: [">"]
{{- end }}
