---
{{ if .Values.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
{{- if .Values.serviceAccountAnnotations }}
  annotations:
  {{- range $key, $val := .Values.serviceAccountAnnotations }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- end}}
