---
{{ if and .Values.serviceAccountName .Values.podSecurityPolicy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nats-streaming-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.podSecurityPolicy }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
{{- end}}
